# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
# Should more or less follow lint and typing settings as found is tox.ini
#
# Once pre-commit package is installed in your environnement, install hooks
# with `pre-commit install`
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
- repo: local
  hooks:
  - id: autoflake
    name: autoflake
    entry: autoflake --check-diff
    language: system
    types: [python]
  - id: flake8
    name: flake8
    entry: flake8 .
    language: system
    types: [python]
  # as per @andersson007 in #768
  # - id: isort
  #   name: isort
  #   entry: isort --check --diff .
  #   language: system
  #   types: [python]
  - id: codespell
    name: codespell
    entry: codespell
    language: system
    types: [file]
